### ISSUE TITLE
Error while buildinging the project

### ISSUE THREAD

**Issue by esQmo** [CovidWorld/android#4]
Hi,
Just cloned the project and followed the instruction, but the project can't build. I'm hitting an error with Gradle:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processGlobalDebugGoogleServices'.
> No matching client found for package name 'covid19'

```

What does error means and could you provide a better guide?

Thank you

**Comment by tomasbecket** [comment]
The problem probably is that the Google services plugin either can't find the google-services.json file or the file is registered for a different package name than you have set in build.gradle.

**Comment by esQmo** [comment]
Solved that one. I was confused with the applicationId which was set to Covid19
