### ISSUE TITLE
Multiple build issues

### ISSUE THREAD

**Issue by esQmo** [CovidWorld/android#5]
Since I cloned this app, I'm unable to build the code. Keep getting tons of errors so a complete guide/documenattio would be appreciated. 
This time I ran into the following error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningGlobalDebug'.
> Keystore file 'C:\*****\****\Covid-19\CovidWorld\app\""' not found for signing config 'release'.

What does this mean? If I get it,it is asking for the debug keystore right?

**Comment by tomasbecket** [comment]
Have you followed the steps in the "Country-specific customisation steps" section of the readme? It seems that you haven't created/copied the app.properties file and filled in the app signing details (keystoreFile, keystorePassword, keyAlias, keyPassword).

**Comment by esQmo** [comment]
Of course I did, but wasn't sure at first place. Solved it already. So what apiURL is it required? The one from the server or Firebase?  @tomaspetrasek tomaspetrasek
