### ISSUE TITLE
Error 401 at start up

### ISSUE THREAD

**Issue by esQmo** [CovidWorld/android#7]
I finally managed to deploy the server to Azure, all set up and running. However, when the app launches, there is a **HTTP 401** error popping.
The method that is being called at start up is the one for registering the device to the server. In the debugger I can see the data being sent but the server returns an error instead so the app can't pass to the next step.
I've found that the error might be that the function needs an authorization, but is set to anonymous

Below is a test made with Postman:
![image](https://user-images.githubusercontent.com/10319812/80264530-5f432200-868c-11ea-8c34-80394d108113.png)

Can you tell which functions is being called by `Api(context).createProfile `call? 

Can you please help me on this one?

**Comment by anonymcek** [comment]
thereis no authentication for this request

**Comment by esQmo** [comment]
Obviously there isn't any. I just wondering why the request is failing @anonymcek
