### ISSUE TITLE
Did this project work for anyone?

### ISSUE THREAD

**Issue by esQmo** [CovidWorld/android#8]
The fact that I'm running into issues hard to figure out and solve and the fact no documentation is provided makes me think this project is somehow a dead project;not suitable for an open source project or the author didn't test it?

Did anyone succeeded to make it work? I would to know because It's been weeks I'm struggling to make it blindly work

**Comment by anonymcek** [comment]
@esQmo this project is currently up and running and under active development. the fact that the documentation is missing is because we do this as a free side job and right now we focus mostly on the development. could you put together the list of issues so we can reply to whole list and maybe figure out what is wtong with your setup?

**Comment by esQmo** [comment]
Thanks for the reply @anonymcek, as I was already losing hope. I appreciate your work, that's why I wanted to implement it as well? But I'm actually having issue that the client app can't pass the Welcome screen.It's pops an error message with status 202 suggesting some async work that needs to complete server side but can't go further.Opened issue to the server repository as well.

Even though I'm not familiar with dotnet environment,I tried my best to make the server run despite countless issues I encountered

**Comment by esQmo** [comment]
![Screenshot_20200426-230115_COVID-19](https://user-images.githubusercontent.com/10319812/80321045-02717400-8812-11ea-8b86-46b2cd45d06d.jpg)
No matter what, I can't pass this screen

**Comment by tomasbecket** [comment]
This is not a valid API response, seems to me the server is not responding with the correct function. Not really an Android issue, please include these details in the opened issue on the server repo.

**Comment by esQmo** [comment]
Thanks I'll include those details there. Thanks for your assistance
